### ISSUE TITLE
Style rules should be warnings, not errors

### ISSUE THREAD

**Issue by localjo** [sindresorhus/eslint-config-xo#37]
While adding xo to my npm start script (ie `"start": "xo '**/*.js' && react-scripts start"`), I noticed that simple style mistakes prevent the whole project from starting. [The default rules in XO](https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js) should make use of both `error` and `warn` settings, reserving `error` only for items that are likely to cause problems (like an undefined variable) while running the code, and using `warn` for anything that's purely stylistic (like an incorrect number of spaces). Of course, this is sometimes a subjective distinction, but the default rules should be a reasonable attempt to distinguish the two. I shouldn't have to override half of the default rules in package.json just to be able to run `xo` as a part of my start scripts without breaking on minor stylistic issues that should be warnings instead of errors.

**Comment by sholladay** [comment]
I personally love that style rules are errors and it's one of the reasons I use XO. If this change were to be implemented, people would be able to merge pull requests on my projects with styles that I don't agree with because warnings can be ignored.

I'll note that using a linter within a `start` script is pretty unusual. The conventional thing is to use it within `test`. By doing that, you can either run `npm test && npm start` to be prudent or you can run just `npm start` to be a daredevil. Even better, you can set up IDE integration to see the errors and warnings inline with your code, then you get to choose which ones you pay attention to or ignore at a much more granular level than what you are proposing here. I know that's not quite what you want, but it seems like a reasonable compromise between what you're going for and the use case that, to my knowledge, most XO users are using it for. Namely, to protect their projects in CI.
